using UnityEngine;
using UnityEditor;
using UIFramework.Data;
using System.Collections.Generic;

namespace UIFramework.Editor
{
    /// <summary>
    /// Custom editor for UI Registry
    /// Validates duplicates and provides better UI
    /// </summary>
    [CustomEditor(typeof(UIRegistry))]
    public class UIRegistryEditor : UnityEditor.Editor
    {
        private SerializedProperty uiConfigsProperty;
        
        private void OnEnable()
        {
            uiConfigsProperty = serializedObject.FindProperty("uiConfigs");
        }
        
        public override void OnInspectorGUI()
        {
            serializedObject.Update();
            
            EditorGUILayout.Space();
            EditorGUILayout.LabelField("UI Registry Configuration", EditorStyles.boldLabel);
            EditorGUILayout.Space();
            
            // Validate button
            if (GUILayout.Button("Validate Registry", GUILayout.Height(30)))
            {
                var registry = target as UIRegistry;
                if (registry.ValidateRegistry())
                {
                    EditorUtility.DisplayDialog("Validation Success", "UI Registry is valid!", "OK");
                }
                else
                {
                    EditorUtility.DisplayDialog("Validation Failed", "UI Registry has errors. Check console for details.", "OK");
                }
            }
            
            EditorGUILayout.Space();
            
            // Auto-generate enum button
            if (GUILayout.Button("Generate ViewId Enum", GUILayout.Height(30)))
            {
                GenerateViewIdEnum();
            }
            
            EditorGUILayout.Space();
            
            // Draw default property
            EditorGUILayout.PropertyField(uiConfigsProperty, true);
            
            serializedObject.ApplyModifiedProperties();
        }
        
        private void GenerateViewIdEnum()
        {
            var registry = target as UIRegistry;
            var configs = registry.UIConfigs;
            
            if (configs.Count == 0)
            {
                EditorUtility.DisplayDialog("Error", "No UI configs found in registry", "OK");
                return;
            }
            
            var enumCode = "// Auto-generated by UIRegistry\n";
            enumCode += "namespace UIFramework.Generated\n{\n";
            enumCode += "    public enum UIViewId\n    {\n";
            
            var viewIds = new HashSet<string>();
            foreach (var config in configs)
            {
                if (!string.IsNullOrEmpty(config.ViewId) && viewIds.Add(config.ViewId))
                {
                    var sanitizedId = config.ViewId.Replace(" ", "");
                    enumCode += $"        {sanitizedId},\n";
                }
            }
            
            enumCode += "    }\n}\n";
            
            // Write to file
            var path = "Assets/Script/UIFramework/Generated/UIViewId.cs";
            System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(path));
            System.IO.File.WriteAllText(path, enumCode);
            
            AssetDatabase.Refresh();
            
            EditorUtility.DisplayDialog("Success", $"Generated UIViewId enum at {path}", "OK");
        }
    }
}
