using UnityEngine;
using UnityEditor;
using UIFramework.Data;
using System.IO;

namespace UIFramework.Editor
{
    /// <summary>
    /// Validates UI Registry on build
    /// Prevents shipping with invalid configuration
    /// </summary>
    public class UIRegistryValidator
    {
        [MenuItem("UIFramework/Validate All Registries")]
        public static void ValidateAllRegistries()
        {
            var registries = AssetDatabase.FindAssets("t:UIRegistry");
            bool allValid = true;
            
            foreach (var guid in registries)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var registry = AssetDatabase.LoadAssetAtPath<UIRegistry>(path);
                
                if (registry != null)
                {
                    Debug.Log($"Validating {path}...");
                    if (!registry.ValidateRegistry())
                    {
                        allValid = false;
                        Debug.LogError($"Validation failed for {path}");
                    }
                }
            }
            
            if (allValid)
            {
                EditorUtility.DisplayDialog("Validation Success", "All UI Registries are valid!", "OK");
            }
            else
            {
                EditorUtility.DisplayDialog("Validation Failed", "Some UI Registries have errors. Check console.", "OK");
            }
        }
        
        [MenuItem("UIFramework/Generate All ViewId Enums")]
        public static void GenerateAllViewIdEnums()
        {
            var registries = AssetDatabase.FindAssets("t:UIRegistry");
            
            foreach (var guid in registries)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var registry = AssetDatabase.LoadAssetAtPath<UIRegistry>(path);
                
                if (registry != null)
                {
                    GenerateViewIdEnum(registry);
                }
            }
            
            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog("Success", "Generated ViewId enums for all registries", "OK");
        }
        
        private static void GenerateViewIdEnum(UIRegistry registry)
        {
            var configs = registry.UIConfigs;
            
            if (configs.Count == 0)
                return;
            
            var enumCode = "// Auto-generated by UIRegistryValidator\n";
            enumCode += "// Do not modify manually\n\n";
            enumCode += "namespace UIFramework.Generated\n{\n";
            enumCode += "    public enum UIViewId\n    {\n";
            enumCode += "        None = 0,\n";
            
            var viewIds = new System.Collections.Generic.HashSet<string>();
            foreach (var config in configs)
            {
                if (!string.IsNullOrEmpty(config.ViewId) && viewIds.Add(config.ViewId))
                {
                    var sanitizedId = config.ViewId.Replace(" ", "").Replace("-", "_");
                    enumCode += $"        {sanitizedId},\n";
                }
            }
            
            enumCode += "    }\n}\n";
            
            var outputPath = "Assets/Script/UIFramework/Generated/UIViewId.cs";
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
            File.WriteAllText(outputPath, enumCode);
            
            Debug.Log($"Generated UIViewId enum at {outputPath}");
        }
    }
}
